config/routes.rb
Siddick::Application.routes.draw do

  resources :posts, :only => [ :index, :show ] do
    collection do
      get "tags/:tag/page/:page" => "posts#index"
      get "tags/:tag" => "posts#index", :as => :tag
      get "page/:page" => "posts#index"
    end
  end
  resource :profile, :only => [ :show, :update ] do
    resources :auth_providers, :only => [ :destroy, :update ]
  end

  match '/auth/:provider/callback', to: 'auth_providers#create'

  devise_for :user

  root :to => "posts#index"
  get "sitemap"    => "home#sitemap", :format => :xml
  get "search"         => "home#search"
  get "about"          => "home#about"
  match "contact"      => "home#contact"
  get "update_caching" => "application#update_caching", :format => :js

  match "*path" => "home#not_found"

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def show
    @title = "Profile"
  end

  def update
    if current_user.update_attributes(params[:user])
      redirect_to profile_path, :notice => "Updated successfully"
    else
      render :show
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def provider_image(name, size = 32)
    "https://github.com/intridea/authbuttons/raw/master/png/#{name}_#{size}.png"
  end
end

app/views/profiles/_sidebar.html.erb
<h3>Add Providers</h3>
<ul class="unstyled">
<% OmniauthProviders.each do |name| %>
  <li>
    <%= image_tag provider_image(name) %>
    <%= link_to name.to_s.humanize, "/auth/#{name}" %>
  </li>
<% end %>
</u>

app/views/profiles/show.html.erb
<%= simple_form_for(current_user, :as => :user, :url => profile_path, :html => { :method => :put }) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :description, :as => :text, :input_html => { :rows => 3, :class => "input-xlarge" } %>

  <div class="control-group">
    <div class="controls">
    <% current_user.auth_providers.each do |auth| %>
      <p>
        <%= image_tag provider_image(auth.provider) %> <%= auth.info.nickname %>
        <% if AuthProvider::AutoPublish[auth.provider.to_sym].present? %>
          <% if auth.auto_publish %>
            <%= link_to "Remove auto-publish", profile_auth_provider_path(auth, :auto_publish => false ), :method => :put %>
          <% else %>
            <%= link_to "Add auto-publish", profile_auth_provider_path(auth, :auto_publish => true ), :method => :put %>
          <% end%>
        <% end%>
        <% if current_user.auth_providers.size > 1 %>
          <%= link_to "Remove", profile_auth_provider_path(auth), :method => "delete", "data-confirm" => "Are you sure?" %>
        <% end %>
      </p>
    <% end %>
    </div>
  </div>

  <div class="form-actions">
  	<%= f.submit "Update", :class => "btn btn-primary", :disable_with => "Updating.." %>
  	<%= link_to "Cancel", profile_path, :class => "btn" %>
  </div>
<% end %>