config/routes.rb
Siddick::Application.routes.draw do

  resources :posts, :only => [ :index, :show ] do
    collection do
      get "tags/:tag/page/:page" => "posts#index"
      get "tags/:tag" => "posts#index", :as => :tag
      get "page/:page" => "posts#index"
    end
  end
  resource :profile, :only => [ :show, :update ] do
    resources :auth_providers, :only => [ :destroy, :update ]
  end

  match '/auth/:provider/callback', to: 'auth_providers#create'

  devise_for :user

  root :to => "posts#index"
  get "sitemap"    => "home#sitemap", :format => :xml
  get "search"         => "home#search"
  get "about"          => "home#about"
  match "contact"      => "home#contact"
  get "update_caching" => "application#update_caching", :format => :js

  match "*path" => "home#not_found"

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  acts_as_taggable
  acts_as_taggable_on :archive

  self.per_page = 10

  attr_accessible :title, :raw_content, :tag_list, :published, :published_at

  validates_presence_of :title, :raw_content, :published_at, :tag_list, :user_id

  scope :published, where(:published => true).order("published_at DESC")

  extend FriendlyId
  friendly_id :title, :use => :slugged

  before_validation :generate_content, :if => :raw_content_changed?
  before_validation :add_archive_list, :if => :published_at_changed?

  def generate_content
    self.content = GenerateContent.render(raw_content)
  end

  def add_archive_list
    self.archive_list = published_at.strftime("%Y, %Y-%m")
  end

  def self.published_tags
    published.tag_counts.order("count DESC")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  caches_page :index, :show

  def index
    @posts  = Post.published.includes(:tags).page(params[:page])
    @posts  = @posts.tagged_with(params[:tag]) if params[:tag].present?
    @title  = params[:tag].try(:humanize) || "Home"
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.haml
%article{:data => { :id => post.to_param, :"updated-at" => post.updated_at, :published => post.published.to_s } }
  - unless @post
    %header
      .pull-right
        %span.icon-tag
        - post.tags.each do |tag|
          = link_to tag.name, tag_posts_path(tag.name)
        %span.icon-time
        = post.published_at.strftime("%d, %b")
      %h3
        %span.icon-calendar
        = link_to post.title, post
  = post.content ? post.content.html_safe : post.raw_content

app/views/posts/_sidebar.html.haml
%ul.nav.nav-list
  - Post.published_tags.each do |tag|
    %li{ :class => tag.name == params[:tag] ? "active" : nil }
      %a{ :href => tag_posts_path(tag.name) }
        %span.icon-tag
        #{tag.name}(#{tag.count})
= render "application/sidebar"

app/views/posts/index.html.haml
.posts
  - if @posts.present?
    = render @posts
  - else
    %p No records found.
= will_paginate @posts

app/views/posts/show.html.erb
<%= render @post %>
<%= render "application/disqus" %>