config/routes.rb
Siddick::Application.routes.draw do

  resources :posts, :only => [ :index, :show ] do
    collection do
      get "tags/:tag/page/:page" => "posts#index"
      get "tags/:tag" => "posts#index", :as => :tag
      get "page/:page" => "posts#index"
    end
  end
  resource :profile, :only => [ :show, :update ] do
    resources :auth_providers, :only => [ :destroy, :update ]
  end

  match '/auth/:provider/callback', to: 'auth_providers#create'

  devise_for :user

  root :to => "posts#index"
  get "sitemap"    => "home#sitemap", :format => :xml
  get "search"         => "home#search"
  get "about"          => "home#about"
  match "contact"      => "home#contact"
  get "update_caching" => "application#update_caching", :format => :js

  match "*path" => "home#not_found"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_admin_user
    current_user.try(:admin?) and current_user
  end

  def authenticate_admin_user!
    unless authenticate_user! and current_admin_user
      redirect_to root_path
    end
  end

  def self.caches_page(*args)
    before_filter :set_page_caching, :actions => args
    super
  end

  def set_page_caching
    @page_caching = self.perform_caching
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    @title ||= @post.try(:title) || params[:action].humanize
  end

  def title=(page_title)
    @title = page_title
  end

  def li_link_to(name, path, *args)
    content_tag("li", :class => (request.path == path) ? "active" : nil ) do
      link_to(name, path, *args)
    end
  end

  def body_class
    "controller-#{params[:controller]} action-#{params[:action]}"
  end

  def post_page_header_class
    class_names = []
    class_names.push("type-#{(@post.type||"post").downcase}") if @post.present? 
    class_names.push("tag tag-#{params[:tag]}") if params[:tag].present? 
    class_names.join(" ")
  end

end

app/views/application/_badges.html.haml
= link_to image_tag("icon/32/github.png",   :alt => "gh"), "https://github.com/siddick"
= link_to image_tag("icon/32/twitter.png",  :alt => "tw"), "https://twitter.com/siddickInside"
= link_to image_tag("icon/32/facebook.png", :alt => "fb"), "http://www.facebook.com/siddick"
= link_to image_tag("icon/32/gplus.png",    :alt => "g+"), "https://plus.google.com/103719245554204460362?prsrc=3"
= link_to image_tag("icon/32/rss.png",      :alt => "rss"), posts_path(:rss), :type => "application/rss+xml", :rel => "alternate"

app/views/application/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'siddick';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

app/views/application/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', <%= (ENV['GOOGLE_ANALYTICS'] || 'UA-31633900-1').to_json.html_safe %>] );
  _gaq.push(['_setDomainName', <%= (ENV['DOMAIN'] || 'siddick.in').to_json.html_safe %>]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/application/_page_header.html.haml
%header{:class => "page-header #{post_page_header_class}"}
  - if content_for? :page_header
    = yield :page_header
  - else
    %h1
      %span.icon
      = title

app/views/application/_share_this.html.erb
<span  class='st_stumbleupon_large' ></span><span  class='st_twitter_large' ></span><span  class='st_facebook_large' ></span><span  class='st_email_large' ></span><span  class='st_sharethis_large' ></span>

app/views/application/_sidebar.html.erb
<%= yield :sidebar %>

app/views/application/_topbar.html.haml
.navbar.navbar-static-top
  .navbar-inner
    .container
      %a.brand{:href => "/", :title => "Siddick"} Si
      .social-icons.pull-right.btn-group
        = render "badges"
      %ul#user_menus.nav.pull-right
        = render 'user_menus' unless @page_caching
      %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse.collapse
        %ul.nav
          = li_link_to "Home", root_path
          = li_link_to "About", about_path
          = li_link_to "Contact", contact_path
        = form_tag search_path, :method => :get, :class => "navbar-search" do
          = text_field_tag "q", params[:q], :class => "search-query", :id => "search-q", :placeholder => "Search"

app/views/application/_user_menus.html.haml
- if user_signed_in?
  %li.dropdown{"data-dropdown" => "dropdown"}
    %a.dropdown-toggle{:href => "#"}
      = image_tag(gravatar_image_url(current_user.email, 18), :alt => current_user.name)
      %b.caret
    %ul.dropdown-menu
      - if current_user.admin?
        %li= link_to icon_with_content('cog', 'Dashboard'), "/admin"
      %li= link_to icon_with_content('user', 'Profile'),  profile_path
      %li= link_to icon_with_content('off', 'Signout'),   destroy_user_session_path

app/views/application/update_caching.js.erb
$('#error_messages').html(<%= flash_block.to_json.html_safe %>);
$('#user_menus').html(<%= render("user_menus").to_json.html_safe %>);
$('head').append(<%= csrf_meta_tags.to_json.html_safe %>);
<% if current_user.try :admin? %>
  $('.admin').show();
<% end %>
$('.dropdown-toggle').dropdown();